#
# /etc/crowdsec/notifications/discord.yaml
#

type: http
name: discord
log_level: info
format: |
  {
    "content": "```\nTriton\n{{range . -}}{{$alert := . -}}{{range .Decisions -}}- {{.Value}} will get **{{.Type}}** for the next '{{.Duration}}'>
  }
url: https://discord.com/api/webhooks/xxxxxxxxxx/xxxxxxxxxx
method: POST
headers:
  Content-Type: application/json


# Enable Discord notifications by uncommenting this block

notifications:
  - discord
